using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static PhotoAtomic.IndentedStrings.IndentedInterpolatedStringHandler;

namespace PhotoAtomic.SourceGen;

/// <summary>
/// Emits PhotoAtomic.Generated.TranslationCatalog into the compiling assembly.
/// The per-invocation intelligence lives in SiteExtraction, shared with the
/// workspace-based extractor of the tool; this class only adapts it to the
/// incremental pipeline (value-equatable models for caching) and renders the
/// generated source. Call sites whose context cannot be resolved are skipped
/// here and reported by the analyzer (PAI18N001).
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class TranslationCatalogGenerator : IIncrementalGenerator
{
    private sealed record Entry(string Key, string? Context, string LegendJoined, string FactsJoined, bool IsValue);

    // Joins list items into one string so the incremental pipeline caches by
    // value; the unit separator (U+001F) never appears in source text.
    private static readonly char ListSeparator = (char)31;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var entries = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => TranslationCall.IsCandidate(node),
                static (syntaxContext, _) => Extract(syntaxContext))
            .SelectMany(static (found, _) => found);

        context.RegisterSourceOutput(entries.Collect(), static (production, all) => Emit(production, all));
    }

    private static ImmutableArray<Entry> Extract(GeneratorSyntaxContext context)
    {
        var extracted = SiteExtraction.FromInvocation((InvocationExpressionSyntax)context.Node, context.SemanticModel);

        var builder = ImmutableArray.CreateBuilder<Entry>(extracted.Length);
        foreach (var entry in extracted)
        {
            builder.Add(new Entry(
                entry.Key,
                entry.Context,
                string.Join(ListSeparator.ToString(), entry.Legend),
                string.Join(ListSeparator.ToString(), entry.Facts),
                entry.IsValue));
        }

        return builder.ToImmutable();
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<Entry> entries)
    {
        if (entries.IsDefaultOrEmpty)
        {
            return;
        }

        var rows = string.Join("\n", entries
            // Identity is (Key, Context, Kind): the same sentence reached from
            // call sites with different legends is still one translation unit.
            .GroupBy(static entry => (entry.Key, entry.Context, entry.IsValue))
            .Select(static group => group.First())
            .OrderBy(static entry => entry.IsValue)
            .ThenBy(static entry => entry.Key, StringComparer.Ordinal)
            .ThenBy(static entry => entry.Context, StringComparer.Ordinal)
            .Select(FormatEntry));

        string source = Indent($$"""
            // <auto-generated/>
            #nullable enable
            namespace PhotoAtomic.Generated
            {
                /// <summary>Every pre-translatable T(...) call site and value found in this assembly.</summary>
                public static class TranslationCatalog
                {
                    public static readonly global::PhotoAtomic.CatalogEntry[] Entries = new global::PhotoAtomic.CatalogEntry[]
                    {
                        {{rows}}
                    };
                }
            }
            """);

        context.AddSource("TranslationCatalog.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string FormatEntry(Entry entry)
    {
        var key = SymbolDisplay.FormatLiteral(entry.Key, quote: true);
        var contextLiteral = entry.Context is null ? "null" : SymbolDisplay.FormatLiteral(entry.Context, quote: true);
        var kind = entry.IsValue
            ? "global::PhotoAtomic.CatalogEntryKind.Value"
            : "global::PhotoAtomic.CatalogEntryKind.Sentence";

        return $"new global::PhotoAtomic.CatalogEntry({key}, {contextLiteral}, "
            + $"new string[] {{ {FormatList(entry.LegendJoined)} }}, "
            + $"new string[] {{ {FormatList(entry.FactsJoined)} }}, {kind}),";
    }

    private static string FormatList(string joined) =>
        joined.Length == 0
            ? string.Empty
            : string.Join(", ", joined
                .Split(ListSeparator)
                .Select(static item => SymbolDisplay.FormatLiteral(item, quote: true)));
}
